version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: integration-tests-ewallet
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DB: test_ewallet
